#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/hodaritoure/.asdf/installs/flutter/1.12.13+hotfix.7-stable"
export "FLUTTER_APPLICATION_PATH=/Users/hodaritoure/Desktop/flutter-apps/summer2020"
export "FLUTTER_TARGET=/Users/hodaritoure/Desktop/flutter-apps/summer2020/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/hodaritoure/.asdf/installs/flutter/1.12.13+hotfix.7-stable/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
